version: 2.0.{build}
shallow_clone: true
clone_depth: 1

services: 
  -mssql2012sp1

install:
  -ps: >- 
     choco install GoogleChrome -y; 
     choco install gb.MongoDB -y;
     .\build\appveyor\install-chromedriver.ps1;
     .\build\appveyor\set-connectionstrings.ps1;

build:
  project: Roadkill.sln
  parallel: true
  verbosity: normal
test:
  categories:
    - Unit
    - Integration
    - Acceptance
