version: 2.0.{build}
shallow_clone: true
clone_depth: 1

services: 
  - mssql2012sp1
  - iis
  - mongodb

environment:
  ConnectionString: Server=(local)\SQL2012SP1;Database=master;User ID=sa;Password=Password12!
  
after_build:
  - ps: >- 
       .\build\appveyor\set-connectionstrings.ps1;

configuration
  - Release;RunOctoPack=true

build:
  project: Roadkill.sln
  parallel: true
  verbosity: normal
  
test:
  categories:
    - Unit
    - Integration

artifacts:
  - path: src\Roadkill.Web\obj\octopacked\*.nupkg

before_deploy:
  - ps: Copy-item -Path lib\configs\connectionStrings.config -Destination src\Roadkill.Web\connectionStrings.config