version: 2.0.{build}
shallow_clone: true
clone_depth: 1

services: 
  -mssql2012sp1

install:
  -ps: >- 
     choco install GoogleChrome -y; 
     choco install gb.MongoDB -y;
     .\\build\\install-chromedriver.ps1; 

before_build:
  -ps: >-
     (gc lib\\Configs\\connectionStrings.dev.config).replace('Server=(local);Integrated Security=true;Connect Timeout=5;database=Roadkill','Server=(local)\\SQL2012SP1;Database=master;User ID=sa;Password=Password12!') | Out-File lib\\Configs\\connectionStrings.dev.config;
     (gc src\\Roadkill.Tests\\Setup\\SqlExpressSetup.cs).replace('Server=(local);Integrated Security=true;Connect Timeout=5;database=Roadkill','Server=(local)\\SQL2012SP1;Database=master;User ID=sa;Password=Password12!') | Out-File src\\Roadkill.Tests\\Setup\\SqlExpressSetup.cs

build:
  project: Roadkill.sln
  parallel: true
  verbosity: normal
test:
  categories:
    - Unit
    - Integration
    - Acceptance
