version: 2.0.{build}
shallow_clone: true
clone_depth: 1

services: 
  - mssql2012sp1
  - iis
  - mongodb

environment:
  ConnectionString: Server=(local)\SQL2012SP1;Database=master;User ID=sa;Password=Password12!
  
after_build:
  - ps: >- 
       .\build\appveyor\set-connectionstrings.ps1;

configuration:
  - Release;RunOctoPack=true

build_script:
  - ps: msbuild roadkill.sln "/p:Configuration=Release;RunOctoPack=true"
  
test:
  categories:
    - Unit
    - Integration

after_test:
  - ps: >- 
       Copy-item -Path "lib\configs\connectionStrings.config" -Destination "src\Roadkill.Web\connectionStrings.config";
       del "src\Roadkill.Web\Web.Debug.config";  
       del "src\Roadkill.Web\Web.Release.config";  

artifacts:
  - path: src\Roadkill.Web\obj\octopacked\*.nupkg

deploy:
  - provider: GitHub
    artifact: src\Roadkill.Web\obj\octopacked\*.nupkg
    draft: false
    prerelease: true
    auth_token: 
        secure: Tat27Q1Y34VPg4IwJk8sqLaw5qRtIyR0huJnSgDowvB2+YRPRtx6vwdLNuMY0S7P
    on:
      branch: master
      appveyor_repo_tag: true       # deploy on tag push only