version: 2.0.{build}
shallow_clone: true
clone_depth: 1

services: 
  - mssql2012sp1
  - iis
  - mongodb

environment:
  ConnectionString: Server=(local)\SQL2012SP1;Database=master;User ID=sa;Password=Password12!
  COVERALLS_REPO_TOKEN:  
    secure: VwMSUv6m2x21/AfgTZY9+hxfSBAjRL0gScLpmwpZk6W0LujzCZ1atvFGBRT5HGrC

cache:
  - packages ->  **\packages.config

build_script:
    - ps: .\build\build.ps1

test:
  categories:
    - Unit
    - Integration

after_test:
  - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[Roadkill*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  src\Roadkill.Tests\bin\release\Roadkill.Tests.dll" -output:coverage.xml
  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  - ps: >- 
       Copy-item -Path "lib\configs\connectionStrings.config" -Destination "src\Roadkill.Web\connectionStrings.config";
       del "src\Roadkill.Web\Web.Debug.config";  
       del "src\Roadkill.Web\Web.Release.config";  
